`**Reference**` https://colab.research.google.com/drive/15Cyy2H7nT40sGR7TBN5wBvgTd57mVKay#forceEdit=true&sandboxMode=true

**Rank / Degree of Tensor**

In [1]:
import tensorflow as tf

In [2]:
rank1_tensor = tf.Variable(['test','ok','Tim'], tf.string)
rank2_tensor = tf.Variable([['sample1', 'sample2'],['value1', 'value2']], tf.string)

In the Following Example we Get to know about the shape must be equal to the both section <br>
**Example:** `if tf.Variable([['sample1', 'sample2', 'sample3'],['value1', 'value2']]` it will show error because of shape

In [3]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

From This `tf.rank()` we get to know about the rank of the `variable` <br>
In Output we Get `numpy = 2` it means that, Thats particular variable content 2 ranks

In [4]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
rank1_tensor.shape, rank2_tensor.shape

(TensorShape([3]), TensorShape([2, 2]))

`.shape` represent the number of element in the following variable

**Changing Shape**

In [6]:
change_shape = tf.ones([1,2,3])
change_shape

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [7]:
change_shape_01 = tf.reshape(change_shape, [3,2,1])

In [8]:
change_shape_01

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [9]:
change_shape_02 = tf.reshape(change_shape_01, [3,-1])
change_shape_02

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

`Linear Regression` <br>
![alt text](../Day_02/image.png)

Let assume a single dot `Y = 1.5 * X + 0.5` <br>
![alt text](<regression fromula.png>)

In [10]:
!pip install -q sklearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-packag

In [13]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc

The libraries you've mentioned in your code serve the following purposes:

1. **`IPython.display.clear_output`**:
   - **Purpose**: This function is used in Jupyter notebooks to clear the output of the current cell. This can be useful when you want to update the output in place, such as during training loops or other iterative processes. Clearing the output makes the notebook cleaner and easier to read.
   - **Example Use**: You might use `clear_output(wait=True)` within a loop to clear the previous output and update with new information, such as progress updates during model training.

2. **`six.moves.urllib`**:
   - **Purpose**: `six` is a Python 2 and 3 compatibility library, and `six.moves` provides a consistent interface for imports that differ between Python 2 and 3. Specifically, `six.moves.urllib` allows you to use the `urllib` package in a way that is compatible across both Python versions.
   - **Example Use**: If you want to make a URL request that works in both Python 2 and 3, you can use `six.moves.urllib` to handle the differences in the `urllib` module across versions.

3. **`tensorflow.compat.v2.feature_column` (as `fc`)**:
   - **Purpose**: This module is part of TensorFlow and provides a way to represent and manage feature columns, which are used to describe how your model should interpret input data. Feature columns can handle various types of data, including numeric, categorical, and embedding columns, making them essential for building models that work with structured data.
   - **Example Use**: Feature columns are often used in conjunction with TensorFlow's `tf.estimator` API to preprocess and feed structured data into a machine learning model.

