In [1]:
import torch

`Tensor` is number, vector, matrix

In [2]:
t1 = torch.tensor(10.)

In [3]:
t1.dtype # give the data Type of the variable

torch.float32

In [4]:
# Creating vector by using tensor
t2 = torch.tensor([1.,2,3,4])
# all element are convert it into float because float is greater than integer
t2, t2.dtype

(tensor([1., 2., 3., 4.]), torch.float32)

In [5]:
# Creating matirx by using tensor
t3 = torch.tensor(
    [[5.0, 6],
    [9,10]]
)
t3, t3.dtype

(tensor([[ 5.,  6.],
         [ 9., 10.]]),
 torch.float32)

In [6]:
t3.shape

torch.Size([2, 2])

In [7]:
# 3d matrix
t4 = torch.tensor([
    [
        [2,3,4],
        [5,6,7],
    ],
    [
        [8,9,10],
        [11,12,13],
    ]
    
])

In [8]:
t4, t4.shape, t4.dtype

(tensor([[[ 2,  3,  4],
          [ 5,  6,  7]],
 
         [[ 8,  9, 10],
          [11, 12, 13]]]),
 torch.Size([2, 2, 3]),
 torch.int64)

## Rule
* Must be equal shape
* datatype must be same

In [9]:
x = torch.tensor(3.0)
y = torch.tensor(4., requires_grad=True)
z = torch.tensor(5., requires_grad=True)
# if we have to perform some operation like derivation so we have to specify that requires_grad is `True`
# it only work with a floating number

In [10]:
sample_arithmatic = x*y+z
print(sample_arithmatic)
# it will work as normal
sample_arithmatic.backward() # it is bascially define the equation that we have to perform operation

# But when we use derivative then
print(x.grad) # It show None because it will not define

tensor(17., grad_fn=<AddBackward0>)
None


`grad` stand for **grdatant**

* x.grde => d(sample_arithmatic)/dx <br>
* y.grde => d(sample_arithmatic)/dy <br>
* z.grde => d(sample_arithmatic)/dz <br>

While computing the derivation we have to derive backward()

In [11]:
y.grad, z.grad # it will execute because we give reuires_grade = True

(tensor(3.), tensor(1.))

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [14]:
# creating a numpy array
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

convert numpy to torch.tensor

In [15]:
np_to_torch = torch.from_numpy(x)
np_to_torch

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

from `torch.tensor` to `numpy`

In [1]:
torch_to_np = np_to_torch.numpy()
torch_to_np

NameError: name 'np_to_torch' is not defined